name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  old_xcode:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.33.0'
          - stable
        xcode-version:
          - '12.5.1'
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - run: TARGET=x86_64-apple-darwin RUST_VERSION=${{ matrix.version }} ci/run.sh

  xcode_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '13.4.1'
          - '14.2.0'
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.version }}
      - run: TARGET=x86_64-apple-darwin RUST_VERSION=nightly ci/run.sh

  target_test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-apple-ios
          - aarch64-apple-ios-sim
          - x86_64-apple-ios
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - run: TARGET=${{ matrix.target }} RUST_VERSION=nightly NOCTEST=1 NORUN=1 ci/run.sh

  style_check:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace -- -D warnings
