[package]
name = "mach-sys"
version = "0.4.3"
authors = [
  # authors of original "mach"
  "Nick Fitzgerald <fitzgen@gmail.com>",
  "David Cuddeback <david.cuddeback@gmail.com>",
  "Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>",

  # authors of "mach2"
  "Yuki Okushi <jtitor@skiff.com>",

  # :-)
  "Delta4 <delta4chat@gmx.com>"
]
license = "BSD-2-Clause OR MIT OR Apache-2.0"
description = "A Rust interface to the user-space API of the Mach 3.0 kernel that underlies OSX."
repository = "https://github.com/delta4chat/mach"
readme = "README.md"
keywords = ["kernel", "macos", "darwin"]
categories = ["api-bindings", "external-ffi-bindings", "no-std", "os"]
edition = "2021"
#include = ["src/**/*", "LICENSE-*", "README.md"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
libc = { version = "0.2", default-features = false }

[features]
default = []
# Uses newer APIs
unstable = []

[workspace]
members = ["mach-test"]

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"

